### ISSUE TITLE
Parameter names should follow standards

### ISSUE THREAD

**Issue by jdhitsolutions** [aliuq/Register-Completion#2]
Your parameter names should follow PowerShell standards. We don't use names like `hash_list`. It should be `Hashlist` or `HashList` depending on your casing preferences. I would also encourage you to use the proper casing. Make the parameter `Command` not `command`. I know it doesn't affect how the function runs but it looks more professional.

**Comment by aliuq** [comment]
Thank you, I will replace these formats
